apiVersion: autoscaling/v1
kind: HorizontalPodAutoScaler
metadata:
 name: project-deployment-hpa
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: project-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 20